name: build docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'build tag prefix to build into docker image'
        required: true
        default: 'trunk'
        type: string
  workflow_call:
    inputs:
      tag:
        description: 'build tag prefix to build into docker image'
        required: true
        default: 'trunk'
        type: string
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1     
#    - name: Build with docker
#      run: docker build --tag ${{ env.REGISTRY }}/${{ github.repository }} .
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish on docker hub
      run: |
        docker buildx build --push \
          --build-arg tag=${{ inputs.tag }} \
          --tag ${{ env.REGISTRY }}/${{ github.repository }}:${{ inputs.tag }}\
          --platform linux/arm64 . 
#    - name: Publish image
#      run: docker push ${{ env.REGISTRY }}/${{ github.repository }}


# vim: set ts=2 et:
